### ISSUE TITLE
Nested semasioFlow dirs when cloning repo

### ISSUE THREAD

**Issue by KrisHeylen** [montesmariana/tutorials#1]
When cloning the semasioFlow repo locally, git creates a directory `./semasioFlow `and the actual code is in a subdir with the same name ` ./semasioFlow/semasioFlow`.  However, the accompanying tutorials (createClouds  and createClouds-loop) assume the directory structure is ./scripts/semasioFlow.
Please, add a warning that when you start off by cloning the repo (rather than using the version on iain under /home/projects/semmetrix/mariana_wolken/cleanWorkflow/scripts/ as the tutorial assumes ), you should rename the cloned dir locally to `./scripts` :

**Comment by montesmariana** [comment]
Good point!
Although I would solve it in a different way.
It's not necessary to rename the cloned dir locally to `.scripts/`. Instead, I would recommend the user to always adapt the path to wherever they have cloned the repository. (My idea eventually is to remove any specific paths from the tutorials, and for the users to add theirs... or even to upload the packages to pypi so they don't need to add anything to the path to begin with).

**Comment by montesmariana** [comment]
I updated the instructions [here](https://qlvl.github.io/nephosem/tutorials.html), what do you think @KrisHeylen?

**Comment by KrisHeylen** [comment]
Yeah, clearer now in createClouds.html! Maybe also update the createClouds-loop.html?
I guess the  homonymous nested directories `./semasioFlow/semasioFlow` when you clone, is more an issue for the semasioFlow repo itself. I will post it there.
